#cloud-config
users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    home: /home/ubuntu
    shell: /bin/bash
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCDZe/jt3LPphmrn7pSfy6fupPlkXn6DmaTdSIuu1XFU912P7GgQrD8ngkqO5pldn9N7LdBG7NpKOM/kpOcO1XprsX62GeFJ8V27lh47DRF8Inbu5SVaR/XllXoaJVnPS8nsff4LW7TdyjgKXWkwV/6dFcn4QkgrY2Y6cOZCy267kLS8pFkpsPpLmn0yATYTVHx/8lyTXgvbqqh2iTUanBxmNdqt22mTRnki4f1B9mv7ONljHX+apSj89gqLnCPlYyXKM54ySXN3n2qqi/iN1/dn2/nIJ12v56PFP+UCo+ybet6Bm4yxGagMBAvvPbuQWXHAzhMxfY+hS7MFGELXrIx aws-key
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC0WGP1EZykEtv5YGC9nMiPFW3U3DmZNzKFO5nEu6uozEHh4jLZzPNHSrfFTuQ2GnRDSt+XbOtTLdcj26+iPNiFoFha42aCIzYjt6V8Z+SQ9pzF4jPPzxwXfDdkEWylgoNnZ+4MG1lNFqa8aO7F62tX0Yj5khjC0Bs7Mb2cHLx1XZaxJV6qSaulDuBbLYe8QUZXkMc7wmob3PM0kflfolR3LE7LResIHWa4j4FL6r5cQmFlDU2BDPpKMFMGUfRSFiUtaWBNXFOWHQBC2+uKmuMPYP4vJC9sBgqMvPN/X2KyemqdMvdKXnCfrzadHuSSJYEzD64Cve5Zl9yVvY4AqyBD aws-key
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCz/wpWmsCxaQyuNFrIachc/q9nUdByoUcBcicl/wnKLFktKp6du9np9Uhmo4M0tVHNnWCt5uNEi2ks/0XEbg2J+4heuAAKEDr/TVbgabiWGclYKpEWZvmw8gsQwfpAKVG4aS2re7wB2uhw82ZqzJVpGm3ne+sNnz5uVrxN8HUnuR2OWJD6bA9l/fBmE6zdObVXgrCJGjZmVyB5GMeTDJKExgoBpLggZn9CNdu7Sx989xtNLehu6SWM+mGCq9Lcu7usiPG+SuEb8XynYaCOnv8+Oko6SYeJ9Omq/E7Eg6vZHqCbBQ81TIZrGKcikLmF2xP7EOprGOSPVewke7ak7vvmOI+p/RfIAyXj1+GYny+esk9G+qDRFXP9uiIlMfH1oGkQkztvSDMH+EOHqgY66NWQJPj83CaWH/euR0MROHXjm1ar3RuN9qcASAnzCOQQ1FMwFkpIV5x0NDRx0Zp1rLt8ZUFykmIuHZI4g9u6RdAiuWUxx9/eF0fXZa6Ju7GEMKeMtZxJJjmB/WCOylbkT+NPw5RcxgyRLKmUAicnYKXBmULY3pQM/Ui8KiCyJqRbLDBAR+XZYsZ7X5uhcuteu8KIfA2xEbInB4Q3c0DnnSih+GEC4pEbz+NOfeCpLJEn4gfyV1S9S08sG62ls8NPFociA9aWmE1oXfcqwvOkkYhxOw== aws-key
ssh_pwauth: false
disable_root: false
package_update: true
packages:
  - apache2
  - libapache2-mod-php

write_files:
  - path: /var/www/html/image.php
    content: |
      <?php
      $ihrname = "Simon Streuli";
      ?>

      <html>
        <head>
          <title><?php echo $ihrname; ?></title>
        </head>
        <body>
          Hier kommt Ihr Text.<br />
          <img src="https://simon-streuli-bucket.s3.us-east-1.amazonaws.com/icon_happy.png?response-content-disposition=inline&X-Amz-Security-Token=IQoJb3JpZ2luX2VjEBsaDGV1LWNlbnRyYWwtMSJGMEQCIE9tP7nyvqCbciakCL7OhNhaXXHl78gc5T8Ga0O0Nb44AiBnyEbA%2BWA1PsJk9F2Bu7pCR%2FX8JtvyJt0td6mpTOCQRir5AggUEAAaDDkyMDcwMTEyMDcxNCIMOaA1lNdaeZc%2FZdLLKtYCJXHCVfUuoq8hj%2FLqR1xfF18wX83clrHHdbksgUuijcFPJa8ATslfgtqiMsi4XdRa%2B7bUNTr9bCnTaCtGmQzbRWakScHsgGuOAy9ImcF6fTEjF%2FZRMdW6PI9jC8gTmMCX3TksKqDQpFU6lLMLF23BYQAiT2m17iBOK8Wr8gbXQYAXNxtnKfOFfm%2Bt4CTO0y5s1dTpFpl2pp9RHyivCZ0ew2ABXKv%2F%2FhSOzkmpw1fXMhP9ST%2BdlzvN8FMk5yy4xP8OjCfWgdFKMSS3xQaNkhOXGauJ9ak06fIzcMMp4ylIDeNJqH4viJjSJUJt70yrdXEGHBVGPX4TVKqwwntbuTHZ%2Fbkc4SgfaOB8mC9GZMJRzE7WAfybiLQLyhXIqIXnxwYY3trjiMKBSN3XgnA2UdT0DYTWPkisVnt9U1sGbjB47DQF9PJt0cQ1i832PjvWHt3vi1IW0%2F9QMNbwtagGOogCcEUu%2BuwSA7NmlbV0Mof6AaBwx5La%2B8nTYgL3kpRJm8wz1prfaJCw6tv6Rt1cANfPzq%2BYo345rUCCsFs92%2FGYFHbbxz8IMGgCllrcqn%2FBYIRpA01yQK9iHAzVWa8yY87XrP03EGshjVYs4R1MxLXiN8rXC4ITYZ0hi7qIhRkSj%2B96hNrHdmq6BxXrBNKCOyBRHnQhUn9%2BfxKL4jpwM6uIGC3ymVnXxKhFVK2gb3qZQS2Ksqnoo3v1E4%2FaUWTBgES28yygKgvkr7ct3wH5fBWhuk%2Fhs3w1KubJ%2FoTpKlxzxcovDkY6xzNPm3dYqvsFiBdl2Zi4E6PF359G9LcIBDal%2BFNRhsFzM8S1&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20230922T114819Z&X-Amz-SignedHeaders=host&X-Amz-Expires=300&X-Amz-Credential=ASIA5MXQQGDFOMDCX5XA%2F20230922%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=c91d375165b000438919968146814c55c0c6f711cc774276c8d96bff079d1032" />

          Platzieren Sie hier notwendige Quellenangaben, z.B. wenn der Inhalt von unsplash kommt.
        </body>
      </html>

runcmd:
  - sudo systemctl restart apache2
