#cloud-config
users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    home: /home/ubuntu
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-rsa xxxaaabbbcccxxx aws-key
  - name: tbz
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    home: /home/ubuntu
    shell: /bin/bash
ssh_pwauth: false
package_update: true
timezone: "Europe/Zurich"
locale: "de_CH"
packages:
  - curl
  - wget
